import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { useWallet } from "@/lib/wallet-context";
import { formatSats } from "@/shared/wallet";

export default function PaymentReviewScreen() {
  const router = useRouter(); const params = useLocalSearchParams<{ reference?: string; amount?: string; memo?: string }>(); const { payReference } = useWallet(); const [isSubmitting, setIsSubmitting] = useState(false);
  const amountSats = Math.floor(Number(params.amount)); const feeSats = Math.max(1, Math.ceil(amountSats * 0.002)); const totalSats = amountSats + feeSats;
  async function confirmPayment() { setIsSubmitting(true); const result = await payReference(params.reference ?? "", amountSats, params.memo ?? ""); setIsSubmitting(false); if (result.error) { haptic.error(); Alert.alert("Pagamento não concluído", result.error); return; } haptic.success(); Alert.alert("Pagamento simulado concluído", "A atividade foi registrada somente no modo de demonstração.", [{ text: "Ver atividade", onPress: () => router.replace("/(tabs)/activity") }]); }
  return <ScreenContainer containerClassName="bg-[#F7F9FC]" safeAreaClassName="bg-[#F7F9FC]"><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><View style={styles.heroIcon}><MaterialIcons name="arrow-upward" size={26} color="#FFFFFF" /></View><Text style={styles.title}>Revisar pagamento</Text><Text style={styles.subtitle}>Confira os dados antes de confirmar. Esta operação é apenas uma simulação local.</Text></View><View style={styles.summaryCard}><View style={styles.summaryRow}><Text style={styles.label}>Você envia</Text><Text style={styles.value}>{formatSats(amountSats)}</Text></View><View style={styles.divider} /><View style={styles.summaryRow}><Text style={styles.label}>Taxa estimada</Text><Text style={styles.value}>{formatSats(feeSats)}</Text></View><View style={styles.divider} /><View style={styles.summaryRow}><Text style={styles.totalLabel}>Total</Text><Text style={styles.totalValue}>{formatSats(totalSats)}</Text></View></View><View style={styles.destinationCard}><Text style={styles.destinationLabel}>DESTINO</Text><Text style={styles.destinationTitle}>Referência Lightning</Text><Text numberOfLines={2} style={styles.reference}>{params.reference ?? "Não informado"}</Text>{params.memo ? <Text style={styles.memo}>{params.memo}</Text> : null}</View><View style={styles.securityNotice}><MaterialIcons name="verified-user" size={20} color="#146C31" /><Text style={styles.securityText}>Ao conectar uma fonte real, a confirmação poderá exigir biometria e validação de invoice.</Text></View><Pressable disabled={isSubmitting} onPress={() => void confirmPayment()} style={({ pressed }) => [styles.confirmButton, (pressed || isSubmitting) && styles.confirmPressed]}><Text style={styles.confirmText}>{isSubmitting ? "Confirmando..." : "Confirmar pagamento simulado"}</Text></Pressable><Pressable disabled={isSubmitting} onPress={() => router.back()} style={({ pressed }) => [styles.cancelButton, pressed && styles.cancelPressed]}><Text style={styles.cancelText}>Cancelar</Text></Pressable></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { gap: 18, padding: 20, paddingBottom: 32 }, hero: { alignItems: "center", gap: 8, paddingHorizontal: 12, paddingTop: 10 }, heroIcon: { alignItems: "center", backgroundColor: "#F7931A", borderRadius: 24, height: 48, justifyContent: "center", width: 48 }, title: { color: "#101828", fontSize: 27, fontWeight: "700", letterSpacing: -0.5 }, subtitle: { color: "#667085", fontSize: 13, lineHeight: 19, textAlign: "center" }, summaryCard: { backgroundColor: "#FFFFFF", borderColor: "#E7EAF0", borderRadius: 18, borderWidth: 1, paddingHorizontal: 17 }, summaryRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", minHeight: 55 }, label: { color: "#667085", fontSize: 14 }, value: { color: "#344054", fontSize: 15, fontVariant: ["tabular-nums"], fontWeight: "600" }, totalLabel: { color: "#101828", fontSize: 16, fontWeight: "800" }, totalValue: { color: "#0A84FF", fontSize: 18, fontVariant: ["tabular-nums"], fontWeight: "800" }, divider: { backgroundColor: "#E7EAF0", height: StyleSheet.hairlineWidth }, destinationCard: { backgroundColor: "#FFFFFF", borderColor: "#E7EAF0", borderRadius: 18, borderWidth: 1, gap: 8, padding: 17 }, destinationLabel: { color: "#667085", fontSize: 10, fontWeight: "800", letterSpacing: 0.8 }, destinationTitle: { color: "#101828", fontSize: 15, fontWeight: "700" }, reference: { color: "#475467", fontFamily: "monospace", fontSize: 12, lineHeight: 18 }, memo: { color: "#667085", fontSize: 13, marginTop: 3 }, securityNotice: { alignItems: "flex-start", backgroundColor: "#F0FBF3", borderColor: "#D7F0DE", borderRadius: 15, borderWidth: 1, flexDirection: "row", gap: 10, padding: 14 }, securityText: { color: "#38744A", flex: 1, fontSize: 12, lineHeight: 17 }, confirmButton: { alignItems: "center", backgroundColor: "#0A84FF", borderRadius: 15, justifyContent: "center", minHeight: 55 }, confirmPressed: { opacity: 0.7 }, confirmText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" }, cancelButton: { alignItems: "center", justifyContent: "center", minHeight: 44 }, cancelPressed: { opacity: 0.6 }, cancelText: { color: "#667085", fontSize: 15, fontWeight: "700" },
});
