import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, ScrollView, Share, StyleSheet, Text, TextInput, View } from "react-native";

import { DemoStatusBanner } from "@/components/demo-status-banner";
import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { useWallet } from "@/lib/wallet-context";
import { formatSats, type LightningInvoice } from "@/shared/wallet";

export default function ReceiveScreen() {
  const router = useRouter();
  const { createReceiveRequest, settleReceiveRequest } = useWallet();
  const [amount, setAmount] = useState(""); const [memo, setMemo] = useState(""); const [invoice, setInvoice] = useState<LightningInvoice | null>(null);
  async function generateRequest() { const result = await createReceiveRequest(Number(amount.replace(/\D/g, "")), memo); if (result.error || !result.invoice) { haptic.error(); Alert.alert("Não foi possível criar", result.error ?? "Tente novamente."); return; } haptic.success(); setInvoice(result.invoice); }
  async function settleRequest() { if (!invoice) return; const result = await settleReceiveRequest(invoice.id); if (result.error) { haptic.error(); Alert.alert("Não foi possível concluir", result.error); return; } haptic.success(); Alert.alert("Recebimento registrado", `${formatSats(invoice.amountSats)} foram adicionados ao saldo de demonstração.`, [{ text: "Ver atividade", onPress: () => router.replace("/(tabs)/activity") }]); }
  if (invoice) return <ScreenContainer containerClassName="bg-[#F7F9FC]" safeAreaClassName="bg-[#F7F9FC]"><ScrollView contentContainerStyle={styles.content}><View style={styles.successHeader}><View style={styles.successIcon}><MaterialIcons name="arrow-downward" size={28} color="#FFFFFF" /></View><Text style={styles.title}>Solicitação criada</Text><Text style={styles.subtitle}>Use esta referência apenas para testar o fluxo. Ela não é uma invoice válida para a rede Lightning.</Text></View><View style={styles.amountCard}><Text style={styles.muted}>Você vai receber</Text><Text style={styles.amountDisplay}>{formatSats(invoice.amountSats)}</Text><Text style={styles.memoDisplay}>{invoice.memo}</Text></View><View style={styles.referenceCard}><Text style={styles.referenceLabel}>REFERÊNCIA DE DEMONSTRAÇÃO</Text><Text selectable style={styles.reference}>{invoice.reference}</Text></View><View style={styles.warning}><MaterialIcons name="info-outline" size={19} color="#B85A00" /><Text style={styles.warningText}>Nesta versão, QR e invoice reais ainda não são gerados. A integração Lightning será ativada somente após revisão de segurança.</Text></View><Pressable onPress={() => void settleRequest()} style={({ pressed }) => [styles.primaryButton, pressed && styles.primaryPressed]}><Text style={styles.primaryButtonText}>Simular recebimento</Text></Pressable><Pressable onPress={() => void Share.share({ message: `Referência de demonstração Divino Bitcoin: ${invoice.reference}` })} style={({ pressed }) => [styles.secondaryButton, pressed && styles.pressed]}><MaterialIcons name="share" size={18} color="#0A84FF" /><Text style={styles.secondaryButtonText}>Compartilhar referência</Text></Pressable></ScrollView></ScreenContainer>;
  return <ScreenContainer containerClassName="bg-[#F7F9FC]" safeAreaClassName="bg-[#F7F9FC]"><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><DemoStatusBanner /><View style={styles.header}><Text style={styles.title}>Receber</Text><Text style={styles.subtitle}>Crie uma solicitação local em Signet/laboratório para testar o fluxo de recebimento.</Text></View><View style={styles.formCard}><Text style={styles.fieldLabel}>VALOR EM SATS</Text><TextInput value={amount} onChangeText={setAmount} placeholder="Ex.: 1.000" placeholderTextColor="#98A2B3" keyboardType="numeric" returnKeyType="done" style={styles.amountInput} /><View style={styles.divider} /><Text style={styles.fieldLabel}>DESCRIÇÃO OPCIONAL</Text><TextInput value={memo} onChangeText={setMemo} placeholder="Ex.: Venda de café" placeholderTextColor="#98A2B3" returnKeyType="done" style={styles.textInput} /></View><View style={styles.infoCard}><MaterialIcons name="bolt" size={21} color="#0A84FF" /><Text style={styles.infoText}>Esta versão cria apenas uma referência local; nenhuma invoice BOLT11, QR code ou conexão Lightning é gerada.</Text></View><Pressable onPress={() => void generateRequest()} style={({ pressed }) => [styles.primaryButton, pressed && styles.primaryPressed]}><Text style={styles.primaryButtonText}>Criar solicitação</Text></Pressable></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { gap: 18, padding: 20, paddingBottom: 34 }, header: { gap: 7, marginTop: 8 }, title: { color: "#101828", fontSize: 29, fontWeight: "700", letterSpacing: -0.6 }, subtitle: { color: "#667085", fontSize: 14, lineHeight: 20 }, formCard: { backgroundColor: "#FFFFFF", borderColor: "#E7EAF0", borderRadius: 18, borderWidth: 1, gap: 8, padding: 18 }, fieldLabel: { color: "#667085", fontSize: 11, fontWeight: "800", letterSpacing: 0.8 }, amountInput: { color: "#101828", fontSize: 30, fontVariant: ["tabular-nums"], fontWeight: "700", paddingVertical: 5 }, textInput: { color: "#101828", fontSize: 16, paddingVertical: 7 }, divider: { backgroundColor: "#E7EAF0", height: StyleSheet.hairlineWidth, marginVertical: 10 }, infoCard: { alignItems: "flex-start", backgroundColor: "#E6F4FE", borderRadius: 15, flexDirection: "row", gap: 11, padding: 14 }, infoText: { color: "#286A9E", flex: 1, fontSize: 13, lineHeight: 18 }, primaryButton: { alignItems: "center", backgroundColor: "#0A84FF", borderRadius: 15, justifyContent: "center", minHeight: 54 }, primaryPressed: { opacity: 0.86, transform: [{ scale: 0.98 }] }, primaryButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" }, successHeader: { alignItems: "center", gap: 9, paddingHorizontal: 10, paddingTop: 10 }, successIcon: { alignItems: "center", backgroundColor: "#30D158", borderRadius: 25, height: 50, justifyContent: "center", width: 50 }, amountCard: { alignItems: "center", backgroundColor: "#0D1117", borderRadius: 22, gap: 8, padding: 22 }, muted: { color: "#B9C3D0", fontSize: 13, fontWeight: "600" }, amountDisplay: { color: "#FFFFFF", fontSize: 31, fontVariant: ["tabular-nums"], fontWeight: "800" }, memoDisplay: { color: "#B9C3D0", fontSize: 13, textAlign: "center" }, referenceCard: { backgroundColor: "#FFFFFF", borderColor: "#E7EAF0", borderRadius: 16, borderWidth: 1, gap: 9, padding: 16 }, referenceLabel: { color: "#667085", fontSize: 10, fontWeight: "800", letterSpacing: 0.8 }, reference: { color: "#101828", fontFamily: "monospace", fontSize: 14, lineHeight: 21 }, warning: { alignItems: "flex-start", backgroundColor: "#FFF7ED", borderColor: "#FDE2C2", borderRadius: 15, borderWidth: 1, flexDirection: "row", gap: 10, padding: 14 }, warningText: { color: "#9A4D09", flex: 1, fontSize: 12, lineHeight: 17 }, secondaryButton: { alignItems: "center", borderColor: "#CFE7FF", borderRadius: 15, borderWidth: 1, flexDirection: "row", gap: 8, justifyContent: "center", minHeight: 52 }, secondaryButtonText: { color: "#0A84FF", fontSize: 15, fontWeight: "700" }, pressed: { opacity: 0.62 },
});
