import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useWallet } from "@/lib/wallet-context";
import { formatDateTime, formatSats } from "@/shared/wallet";

export default function TransactionDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { state } = useWallet(); const transaction = state?.transactions.find((item) => item.id === id);
  if (!transaction) return <ScreenContainer className="items-center justify-center p-6"><Text style={styles.notFound}>Movimento local não encontrado.</Text></ScreenContainer>;
  const incoming = transaction.direction === "incoming"; const total = incoming ? transaction.amountSats : transaction.amountSats + transaction.feeSats;
  return <ScreenContainer containerClassName="bg-[#F7F9FC]" safeAreaClassName="bg-[#F7F9FC]"><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><View style={[styles.heroIcon, incoming ? styles.incomingIcon : styles.outgoingIcon]}><MaterialIcons name={incoming ? "arrow-downward" : "arrow-upward"} size={28} color={incoming ? "#16803A" : "#B85A00"} /></View><Text style={styles.status}>{incoming ? "Recebido" : "Enviado"} em demonstração</Text><Text style={[styles.amount, incoming ? styles.incomingAmount : styles.outgoingAmount]}>{incoming ? "+" : "−"}{formatSats(total)}</Text><Text style={styles.date}>{formatDateTime(transaction.createdAt)}</Text></View><View style={styles.detailCard}><DetailRow label="Status" value="Concluída" /><DetailRow label="Descrição" value={transaction.memo} /><DetailRow label="Contraparte" value={transaction.counterparty} /><DetailRow label="Valor" value={formatSats(transaction.amountSats)} />{!incoming ? <DetailRow label="Taxa estimada" value={formatSats(transaction.feeSats)} /> : null}</View><View style={styles.referenceCard}><Text style={styles.referenceLabel}>REFERÊNCIA</Text><Text selectable style={styles.reference}>{transaction.reference}</Text></View><View style={styles.disclaimer}><MaterialIcons name="science" size={19} color="#085EAF" /><Text style={styles.disclaimerText}>Este registro é local e pertence ao modo de demonstração. Não representa uma transação em Bitcoin ou Lightning Network.</Text></View></ScrollView></ScreenContainer>;
}
function DetailRow({ label, value }: { label: string; value: string }) { return <View style={styles.detailRow}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>; }
const styles = StyleSheet.create({
  content: { gap: 18, padding: 20, paddingBottom: 32 }, hero: { alignItems: "center", gap: 7, paddingTop: 15 }, heroIcon: { alignItems: "center", borderRadius: 26, height: 52, justifyContent: "center", width: 52 }, incomingIcon: { backgroundColor: "#E9F9EE" }, outgoingIcon: { backgroundColor: "#FFF3E5" }, status: { color: "#475467", fontSize: 14, fontWeight: "600", marginTop: 3 }, amount: { fontSize: 30, fontVariant: ["tabular-nums"], fontWeight: "800", letterSpacing: -0.8 }, incomingAmount: { color: "#16803A" }, outgoingAmount: { color: "#B85A00" }, date: { color: "#667085", fontSize: 13 }, detailCard: { backgroundColor: "#FFFFFF", borderColor: "#E7EAF0", borderRadius: 18, borderWidth: 1, overflow: "hidden" }, detailRow: { alignItems: "flex-start", borderBottomColor: "#E7EAF0", borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", justifyContent: "space-between", minHeight: 56, paddingHorizontal: 16, paddingVertical: 14 }, detailLabel: { color: "#667085", flex: 0.45, fontSize: 14 }, detailValue: { color: "#1D2939", flex: 0.55, fontSize: 14, fontWeight: "600", textAlign: "right" }, referenceCard: { backgroundColor: "#FFFFFF", borderColor: "#E7EAF0", borderRadius: 16, borderWidth: 1, gap: 9, padding: 16 }, referenceLabel: { color: "#667085", fontSize: 10, fontWeight: "800", letterSpacing: 0.8 }, reference: { color: "#344054", fontFamily: "monospace", fontSize: 12, lineHeight: 18 }, disclaimer: { alignItems: "flex-start", backgroundColor: "#E6F4FE", borderRadius: 15, flexDirection: "row", gap: 10, padding: 14 }, disclaimerText: { color: "#286A9E", flex: 1, fontSize: 12, lineHeight: 17 }, notFound: { color: "#667085", fontSize: 15 },
});
